### ISSUE TITLE
Replace homepage by the features page

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum.github.io#62]
Hello 🙂,

So far, our homepage sucks. I propose as a short term to replace it by the features pages. What do you think?

**Comment by Grummfy** [comment]
seems ok, but perhaps you can elaborate a bit more about what you expect to see on the home page, because I'm not sure that just the feature one will be enough

**Comment by Hywan** [comment]
Having a better homepage can be addressed in another issue, but so far, the current homepage looks like a draft…

**Comment by mikaelrandy** [comment]
I agree.

Ask ourself about "who come on atoum.org website and for what usage ?"
I think the answer is "people who look for what is atoum", and we have to made an homepage who quickly expose main atoum's strengths.

Maybe not the "Features" page as it is, because it's a extended description.
Maybe a landing page like [Silex](http://silex.sensiolabs.org/) ?
I love [Hoa's homepage](https://hoa-project.net/en/) too

**Comment by agallou** [comment]
how about something like this ?

![screen shot 2017-03-26 at 23 29 46-fullpage](https://cloud.githubusercontent.com/assets/320372/24335387/3552e91c-127c-11e7-834e-8644a26511c6.png)
